title: Deacon Hagop Ketchedjian
logo: /assets/headshot.png
description: Candidate for Priesthood in the Eastern Prelacy of the USA & Deacon at St. Stephen's Armenian Apostolic Church in Watertown, MA.
theme: jekyll-theme-minimal
